# Generated by Django 2.2.2 on 2019-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='about us')),
                ('twitter', models.URLField(default='https://www.twitter.com', max_length=255)),
                ('facebook', models.URLField(default='https://www.facebook.com', max_length=255)),
                ('tos', models.TextField(default='tos')),
                ('privacy', models.TextField(default='privacy')),
            ],
        ),
    ]
